server.port=8084
spring.application.name=alert-service
spring.threads.virtual.enabled=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized
