server.port=8086
spring.application.name=rag-service
spring.threads.virtual.enabled=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized
